# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_J1:
    has_position_limits: true
    min_position: -3
    max_position: 3
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: true
    max_acceleration: 3
  joint_J2:
    has_position_limits: true
    min_position: -3
    max_position: 3
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: true
    max_acceleration: 3
  joint_J3:
    has_position_limits: true
    min_position: -3
    max_position: 3
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: true
    max_acceleration: 3
  joint_J4:
    has_position_limits: true
    min_position: -3
    max_position: 3
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: true
    max_acceleration: 3
  joint_J5:
    has_position_limits: true
    min_position: -3
    max_position: 3
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: true
    max_acceleration: 3
  joint_J6:
    has_position_limits: true
    min_position: -3
    max_position: 3
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: true
    max_acceleration: 3