msa6:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Group Position Controllers ---------------------------------------
  # Allows to send single ROS msg of Float64MultiArray to all joints
  joint_group_position_controller:
     type: effort_controllers/JointGroupPositionController
     joints:
        - joint1
        - joint2
        - joint3
        - joint4
        - joint5
        - joint6
     joint1:
        pid: {p: 500.0, i: 10, d: 50}
     joint2:
        pid: {p: 500.0, i: 10, d: 50}
     joint3:
        pid: {p: 500.0, i: 10, d: 50}
     joint4:
        pid: {p: 500.0, i: 10, d: 50}
     joint5:
        pid: {p: 500.0, i: 10, d: 50}
     joint6:
        pid: {p: 500.0, i: 10, d: 50}

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint1
    pid: {p: 500.0, i: 10, d: 50}
