msa6:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Group Position Controllers ---------------------------------------
  # Allows to send single ROS msg of Float64MultiArray to all joints
  joint_group_position_controller:
     type: effort_controllers/JointGroupPositionController
     joints:
        - joint_J1
        - joint_J2
        - joint_J3
        - joint_J4
        - joint_J5
        - joint_J6
     joint_J1:
        pid: {p: 500.0, i: 10, d: 50}
     joint_J2:
        pid: {p: 500.0, i: 10, d: 50}
     joint_J3:
        pid: {p: 500.0, i: 10, d: 50}
     joint_J4:
        pid: {p: 500.0, i: 10, d: 50}
     joint_J5:
        pid: {p: 500.0, i: 10, d: 50}
     joint_J6:
        pid: {p: 500.0, i: 10, d: 50}

  # Position Controllers ---------------------------------------
  joint_J1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_J1
    pid: {p: 500.0, i: 10, d: 50}
